### PR TITLE
Simplified browsersync with tests, fixes #3, fixes #1

### LINKED ISSUE #1: Excited to see this, how can I help?
So excited to see this out there. Is there a way that I can help it in the maturing process? I see there are test failures.

### LINKED ISSUE #3: feat: add `browsersync` helper
Add a custom command to start browsersync from the host.

Maybe `ddev browsersync` ?

### PR DESCRIPTION
**Pull request by rfay**
This uses a simpler way of running browsersync that should run in all project types, and adds tests and a custom `ddev browsersync` command.

You can try this out with these techniques:
* `ddev get https://github.com/rfay/ddev-browsersync/tarball/20220529_simplified_browsersync`
* Check out the PR into a directory and `ddev get /path/to/directory`

You can run tests with `bats tests`

Testing:

- [x] Try it out! with just the basics, including just using the `ddev browsersync` command
- [x] Try it out with laravel mix using the instructions
- [x] Review automated tests

Note that README.md now has into about how to increase `fs.inotify.max_user_watches`, Mostly that's not an issue with the Docker Desktop or Colima defaults.
* https://github.com/abiosoft/colima/issues/319

### CODE REVIEW

**Comment by tyler36** [comment]
I think `vendors` should also be ignored out-of-the-box.

**Comment by rfay** [comment]
You bet, feel free to do a suggestion comment.

Please approve the tests so they can run, thanks!

**Comment by rfay** [comment]
Please review this @tyler36 - I think it's ready to go now. Also please approve running the workflow.

**Comment by tyler36** [comment]
Is there a way to clear up the "Executed pre-install..." message?

```shell
ddev get https://github.com/rfay/ddev-browsersync/tarball/20220529_simplified_browsersync
Downloading https://github.com/rfay/ddev-browsersync/tarball/20220529_simplified_browsersync 
20220529_simplified_browsersync_1649000965.tar.gz 90.49 KiB / ? [------=--------------------------------------------------------------------------------] 926.57% 0s 
Executed pre-install action if ! ( ddev debug capabilities 2>/dev/null | grep multiple-dockerfiles >/dev/null 2>&1 ) ; then
  echo "This add-on requires DDEV v1.19.3 or higher, please upgrade." && exit 2
fi
, output=. 
Installed file /home/user13/code/test-sync/.ddev/docker-compose.browsersync.yaml 
```

**Comment by tyler36** [comment]
Working:
- Drupal 9
- Laravel 9 via laravel-mix

❌ Broken on Laravel 9 via `ddev browsersync`
I couldn't get `ddev browsersync` to detect changes at all. I tried updating the `file`  key to various directories, even setting it to `readme.md` at one point.

Then I found the problem:  `ignore: ["node_modules", filesdir, "vendor"],`
On default Laravel install, `filesdir`  is empty

```js
// browser-sync.js
let docroot = process.env.DDEV_DOCROOT;
let filesdir = process.env.DDEV_FILES_DIR;
let url = process.env.DDEV_HOSTNAME;

console.log(docroot);
console.log(filesdir);
console.log(url);
```

```shell
$ ddev browsersync
public

test-sync.ddev.site
[Browsersync] Proxying: http://localhost
```

That is cause the script to break

**Comment by tyler36** [comment]
The following doesn't work:
```
filesdir = '';

module.exports = {
    ignore: ["node_modules", filesdir, "vendor"],
```

The following works:
```
filesdir = null;

module.exports = {
    ignore: ["node_modules", filesdir, "vendor"],
```

**Comment by tyler36** [comment]
> Note that README.md now has into about how to increase fs.inotify.max_user_watches, but it's not clear how to persist that,

The PR watches the `docroot` folder which I think is overkill.

For Lavavel project, I watch the following:

```js
  files: [
    'app/**/*.php',
    'resources/views/**/*.php',
    'public/**/*.(js|css)'
  ],
```

For Drupal projects, I use
```js
  files: [
    'web/modules/custom',
    'web/themes/custom',
    'web/sites/default'
  ],
```

Would this be better as a readme item, or can `ddev get` use a `post-install` hook to re-write `brower-sync.js` based on tthe current project type?

**Comment by rfay** [comment]
Thanks for taking a look.

* We'll fix the empty filesdir issue, thanks for catching that.  You can just do a suggestion in a comment in your review and I can commit it... It's easier that way. 
* Limiting the scope of the files is certainly appropriate, and is already in the readme at least a little. But making the default work without people even having to think about it is a good thing. If you have a generic suggestion I'm sure interested! Rewriting the browser-sync.js  for every project type (and unknown project types as well) sounds harsh and unmaintainable. 
* The maintainer of colima already bumped the default max_user_watches to 1M, so it's probably not a big issue in most places now.

**Comment by rfay** [comment]
> "Is there a way to clear up the "Executed pre-install..." message?" 

That's certainly a good thing to do... And it can't be done without a change to ddev, which I think we should figure out. But even though that output is ugly, IMO it shouldn't delay this.

**Comment by rfay** [comment]
I tried to implement your suggestion for filesdir in https://github.com/tyler36/ddev-browsersync/pull/8/commits/e5ed7c637369e612e06512db6611684db1f0109d - let me know if that's good.

**Comment by tyler36** [comment]
Thanks, tested and works as expected: https://github.com/tyler36/ddev-browsersync/commit/e5ed7c637369e612e06512db6611684db1f0109d

Once the workflow tests pass, I'll merge and release.

**Pull request merged**
